### PR TITLE
When forcing the JS parser, use the modern name

### PR DESCRIPTION
**Pull request by BPScott**
This avoids a deprecation notice

With thanks to @robertoentringer for spotting this

### CODE REVIEW

**Comment by Standard8** [comment]
@BPScott we've been hitting this on a project we're working. We have a workaround for it that we can easily use, but I was just wondering if you had any plans to release a new version soon?

**Comment by BPScott** [comment]
Alas I've not got the keys to npm. @not-an-aardvark could you push out a 3.1.1 point release. (or setup publish rights if you want [me](https://www.npmjs.com/~bpscott) to be self sufficient)

**Comment by not-an-aardvark** [comment]
@BPScott Added you to the package on npm. (Sorry, not sure if it sent out a notification email automatically.)

**Comment by BPScott** [comment]
Didn't get an email but I've got access, thanks :)

v3.1.1 has just been published with this change.

**Pull request merged**
