### PR TITLE
feat: expose reporter api

### LINKED ISSUE #39: Expose report-related APIs in another package
Currently, all the APIs are not exposed, so that it can't be reused by other linter-plugin, e.g. [tslint-plugin-prettier](https://github.com/ikatyang/tslint-plugin-prettier/tree/master/src/utils) (currently just copy-paste implementations from this repo).

It'd be better to expose report-related APIs in another package (since this repo has peerDeps for eslint), so that it can be reused in different linter plugin to have consistent behavior.

Suggested API

```ts
export declare function showInvisibles(str: string): string;
export declare function reportDifferences(source: string, formatted: string, reporters: Reporters);

export interface Reporters {
  reportInsert: (offset: number, text: string, message: string) => void;
  reportDelete: (offset: number, text: string, message: string) => void;
  reportReplace: (offset: number, deleteText: string, insertText: string, message: string) => void;
}
```

### PR DESCRIPTION
**Pull request by ikatyang**
Fixes #39

### CODE REVIEW

**Comment by zertosh** [comment]
Ok, so I had a bit of time to think about this and I'm not sure this is a great approach. Besides, the lack of docs and testing – to make sure this doesn't change w/o breaking you – an API that takes reporter functions creates a larger surface area than necessary.

What is now `reportDifferences`, should really be a `generateDifferences` that returns an array of insert/delete/replace ops, then you call your own reporter on them.

I'll put something together later today since it turns out I also kinda need this for a clang-format linter I'm working on.

**Comment by ikatyang** [comment]
I think this package can be separated into three part (`eslint-plugin-prettier`, `generate-differences `and `show-invisible`), all of them are useful and reusable, but it seems you don't want to separate them, so I just refactor them to have minimum changes for exposing API.

maybe we can have something like this? 

```ts
function generateDifferences(source: string, target: string): Result[];
interface Result {
  operation: Operation;
  offset: number;
  insertText: string;
  deleteText: string;
}
enum Operation {
  Insert,
  Delete,
  Replace,
}
```

**Comment by ikatyang** [comment]
@zertosh @not-an-aardvark, is this PR okay or what should I do?

**Comment by zertosh** [comment]
I don't have anything constructive to add.

**Comment by ikatyang** [comment]
Can we get this merged and publish? Thanks. 😅

**Comment by not-an-aardvark** [comment]
Oops, I forgot to publish it. I'll do that now.

**Comment by not-an-aardvark** [comment]
Published as v2.2.0.

**Pull request merged**
