### PR TITLE
Remove `Sponsors` and `Backers` section from README.md

### PR DESCRIPTION
**Pull request by fisker**
For the fundings, I suggest you open a joined account on opencollective, but before that I guess we can use @JounQin's personal account.

But I don't think display all those unrelated orgs in README is the right thing.

### CODE REVIEW

**Comment by JounQin** [comment]
Sure

**Comment by JounQin** [comment]
@fisker For opencollective, how can I `join prettier`?

**Comment by fisker** [comment]
I  mean  a new account, like  other projects did. https://github.com/prettier/plugin-ruby/blob/main/.github/FUNDING.yml

**Comment by JounQin** [comment]
> I mean a new account, like other projects did. [https://github.com/prettier/plugin-ruby/blob/main/.github/FUNDING.yml](https://github.com/prettier/plugin-ruby/blob/main/.github/FUNDING.yml?rgh-link-date=2022-08-13T01%3A21%3A04Z)

OK, that seems to make sense. I'll do it later.

**Pull request merged**
