### PR TITLE
chore(CI): add tests for ESLint 8

### LINKED ISSUE #427: Support ESLint 8.x
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

It would be awesome to have official ESLint 8 support. 👊
I'm happy to help where I can of course 🙂

### PR DESCRIPTION
**Pull request by MichaelDeBoey**
ESLint v8.0.0 is [released](https://eslint.org/blog/2021/10/eslint-v8.0.0-released) 🎉

devDependency compatibility with ESLint 8:

- [x] [`@graphql-eslint/eslint-plugin`](https://github.com/dotansimha/graphql-eslint) (https://github.com/dotansimha/graphql-eslint/issues/595)
  - [x] https://github.com/dotansimha/graphql-eslint/pull/683
  - [x] [`v2.3.0`](https://github.com/dotansimha/graphql-eslint/releases/tag/%40graphql-eslint%2Feslint-plugin%402.3.0)
- [x] [`eslint-plugin-eslint-plugin`](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin) (https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/issues/175)
  - [x] https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/119
  - [x] https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/151
  - [x] https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/186
  - [x] https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/pull/212
  - [x] [`v4.0.0-0`](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/blob/master/CHANGELOG.md#v400-0)
  - [x] [`v4.0.0`](https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin/releases/tag/v4.0.0)
- [ ] [`eslint-plugin-graphql`](https://github.com/apollographql/eslint-plugin-graphql) (https://github.com/apollographql/eslint-plugin-graphql/issues/310)
  - [ ] PR
  - [ ] Release
- [ ] [`eslint-plugin-node`](https://github.com/mysticatea/eslint-plugin-node) (https://github.com/mysticatea/eslint-plugin-node/issues/294)
  - [ ] https://github.com/mysticatea/eslint-plugin-node/pull/224
  - [ ] https://github.com/mysticatea/eslint-plugin-node/pull/295
  - [ ] Release
- [x] [`vue-eslint-parser`](https://github.com/vuejs/vue-eslint-parser)
  - [x] https://github.com/vuejs/vue-eslint-parser/pull/122
  - [x] ~~Release~~

---

I wanted to update `eslint-config-prettier`, `eslint-plugin-eslint-plugin`, `eslint-plugin-node` & `vue-eslint-parser` to their latest minor, but that would break CI on the older ESLint/Node versions

If wanted, I can do it in this PR or make a second PR with all the breaking changes.
**Edit**: This can be done without a breaking change after #429 is merged

---

Closes #427

### CODE REVIEW

**Comment by BPScott** [comment]
If you rebase, a lot of this goes away. It looks like CI has passed successfully though, so it seems we're all v8 compliant.

I'd prefer to avoid testing pre-release versions though if possible so I'm tempted to close this, and we can revisit once v8.0.0 is released.

**Comment by MichaelDeBoey** [comment]
@BPScott Rebased onto `master`

I've also updated all ESLint-related dependencies to their latest versions.

**Comment by Belco90** [comment]
Hey! When will be this new version published? It didn't trigger any new release since it was merged as a chore, but this should be a new minor adding compatibility for ESLint v8.

**Comment by BPScott** [comment]
This PR changed development-only dependencies and what we run in CI. There were no code changes required to support eslint 8, what is already published to npm is sufficient.

**Comment by martin-badin** [comment]
Hi, I think you need to update peerDependencies as well.
```
 "peerDependencies": {
    "eslint": ">=7.28.0",
    "prettier": ">=2.0.0"
  },
  ```

**Comment by BPScott** [comment]
`>=7.28.0` means anything above version including v8.ANYTHING. This package continues to work with both eslint v7.28 and up and v8 and up.

**Pull request merged**
