### PR TITLE
feat: support `@graphql-eslint/eslint-plugin` out of box

### LINKED ISSUE #411: incompatible with `@graphql-eslint/eslint-plugin` out of box
That's because of `eslint-plugin-graphql`.

It wraps GraphQL source code into a js string tag, we supported this usage by mapping `graphql` to `babel` parser at https://github.com/prettier/eslint-plugin-prettier/pull/11.

But `@graphql-eslint/eslint-plugin` works with a custom estree-compatible parser, then the mapping is incorrect for it.

I'm going to raise a PR to support these two plugins/processors at the same time!

Related to https://github.com/dotansimha/graphql-eslint/issues/395

### PR DESCRIPTION
**Pull request by JounQin**
close #411

support original `eslint-plugin-graphql` at the same time

### CODE REVIEW

**Comment by JounQin** [comment]
@BPScott Any idea to improve the test cases?

**Comment by JounQin** [comment]
@BPScott Like https://github.com/prettier/stylelint-prettier/pull/22

I think we should just ignore such code blocks as `stylelint-prettier`.

Considering:

```js
export const content = gql`
  scalar Test
`
```

Prettier will be run twice for the `.js` file and the virtual file `0_document.graphql`.

**Comment by JounQin** [comment]
@BPScott Any chance to review this PR first?

**Review by BPScott — APPROVED** [review]

**Comment by BPScott** [comment]
After far far too long, v3.4.1  has been released that contains this fix.

**Pull request merged**
