### PR TITLE
[DO NOT MERGE] feat: expose reporter api

### PR DESCRIPTION
**Pull request by ikatyang**
demo #39

### CODE REVIEW

**Comment by zertosh** [comment]
I like the idea, but it seems like you're pulling out stuff into "utils" for the sake of pulling them out.

**Comment by ikatyang** [comment]
This PR is just for demo, since the exposed API should in another package due to peerDeps. 😅

**Comment by not-an-aardvark** [comment]
We could always remove the `eslint` peerDependency if we're exposing an API that works without eslint.

**Comment by ikatyang** [comment]
OK, I'll reopen and modify this PR later.

**Comment by ikatyang** [comment]
I somehow can't reopen this PR, so I create a new one #41.

**Pull request closed without merging**
