### PR TITLE
chore: skip formatting inline scripts in pug files

### PR DESCRIPTION
**Pull request by JounQin**
related: https://github.com/valpackett/eslint-plugin-pug and #617

### CODE REVIEW

**Review by BPScott — APPROVED** [review]

**Comment by BPScott** [comment]
Could we add some tests, in the same style as the eslint-plugin-svelte tests?

**Comment by JounQin** [comment]
> Could you add a test, in the same style as the eslint-plugin-svelte test?

OK, I'll add a test case when I'm free.

**Comment by JounQin** [comment]
@BPScott I just added the test case for pug files, do you want to review again?

**Review by BPScott — APPROVED** [review]
Thanks for adding the test case!

**Pull request merged**
